default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  socket: /var/run/mysqld/mysqld.sock
  host: localhost
  # For details on connection pooling, see Rails configuration guide http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5
  username: <%= ENV['RAILS_DATABASE_USER'.freeze] %>
  password: <%= ENV['RAILS_DATABASE_PASSWORD'.freeze] %>

staging:
  <<: *default
  database: clearcourts_staging

production:
  <<: *default
  database: clearcourts_production

development: &development
  <<: *default
  database: clearcourts_development
  # overrides for your machine in database.development.yml --> example: OSX socket location
  <%= begin;YAML.load_file('config/database.development.yml'.freeze).to_json.split(/(\{|\})/)[2].to_s.gsub('"'.freeze, ''.freeze).gsub(':'.freeze, ': '.freeze).gsub(",".freeze, "\n  ".freeze); rescue Errno::ENOENT; ''.freeze; end %>

test:
  <<: *development
  database: clearcourts_test
  <%= begin;YAML.load_file('config/database.test.yml'.freeze).to_json.split(/(\{|\})/)[2].to_s.gsub('"'.freeze, ''.freeze).gsub(':'.freeze, ': '.freeze).gsub(",".freeze, "\n  ".freeze); rescue Errno::ENOENT; ''.freeze; end %>
